// std_options.zig - Standard library options for embedded targets
// This file is automatically generated by Zant codegen
// Required by Zig to define page_size_min for freestanding targets

pub const page_size_min = 4096;
