const std = @import("std");
const zant = @import("zant");
const IR = @import("IR_zant");

// --- zant IR
const GraphZant = IR.GraphZant;
const TensorZant = IR.TensorZant;
// --- utils
pub const utils = @import("utils.zig");
// --- onnx
const onnx = zant.onnx;
const ModelOnnx = onnx.ModelProto;
// --- allocator
const allocator = zant.utils.allocator.allocator;
// --- codegen
const codegenParameters = @import("parameters/parameters.zig");

pub fn write(generated_path: []const u8) !void {

    //initializing writer for static_parameters file
    const params_file_path = try std.fmt.allocPrint(allocator, "{s}static_parameters.zig", .{generated_path});
    defer allocator.free(params_file_path);
    var param_file = try std.fs.cwd().createFile(params_file_path, .{});
    std.log.info("\n .......... file created, path:{s}", .{params_file_path});
    defer param_file.close();

    //create writer parameters file
    const writer = param_file.writer();

    // Generate tensor initialization code in the static_parameters.zig file
    try codegenParameters.write_parameters(writer);

    // Create std_options.zig file for embedded targets
    const std_options_file_path = try std.fmt.allocPrint(allocator, "{s}std_options.zig", .{generated_path});
    defer allocator.free(std_options_file_path);
    var std_options_file = try std.fs.cwd().createFile(std_options_file_path, .{});
    std.log.info("\n .......... file created, path:{s}", .{std_options_file_path});
    defer std_options_file.close();

    const std_options_writer = std_options_file.writer();
    try std_options_writer.print(
        \\// std_options.zig - Standard library options for embedded targets
        \\// This file is automatically generated by Zant codegen
        \\// Required by Zig to define page_size_min for freestanding targets
        \\
        \\const std = @import("std");
        \\
        \\pub const page_size_min = 4096;
        \\
    , .{});
}
