name: Zig Benchmarks

on:
  push:

jobs:
  test:
    name: Run Zig Benchmarks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.15.2 # Current zig version supported by the library

      - name: Run Benchmarks
        run: zig build --release=fast -Dtarget=native -Dfull=true benchmark > benchmarks/latest_benchmark.txt 2>&1

      - name: Save benchmark results
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-results
          path: benchmarks/latest_benchmark.txt
